// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const getQrcodeImage = `-- name: GetQrcodeImage :one
SELECT id, image FROM qrcode WHERE id = ?1
`

type GetQrcodeImageRow struct {
	ID    int64
	Image []byte
}

func (q *Queries) GetQrcodeImage(ctx context.Context, id int64) (GetQrcodeImageRow, error) {
	row := q.db.QueryRowContext(ctx, getQrcodeImage, id)
	var i GetQrcodeImageRow
	err := row.Scan(&i.ID, &i.Image)
	return i, err
}

const getQrcodeTitle = `-- name: GetQrcodeTitle :one
SELECT id, name FROM qrcode WHERE id = ?1
`

type GetQrcodeTitleRow struct {
	ID   int64
	Name sql.NullString
}

func (q *Queries) GetQrcodeTitle(ctx context.Context, id int64) (GetQrcodeTitleRow, error) {
	row := q.db.QueryRowContext(ctx, getQrcodeTitle, id)
	var i GetQrcodeTitleRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const upsertQrcode = `-- name: UpsertQrcode :exec
INSERT OR REPLACE INTO qrcode (id, name, image)
VALUES (?1, ?2, ?3)
`

type UpsertQrcodeParams struct {
	ID    int64
	Name  sql.NullString
	Image []byte
}

func (q *Queries) UpsertQrcode(ctx context.Context, arg UpsertQrcodeParams) error {
	_, err := q.db.ExecContext(ctx, upsertQrcode, arg.ID, arg.Name, arg.Image)
	return err
}
